@version: 3.29

source s_pfsense {
    network(ip(0.0.0.0) port(514) transport("udp"));
};

destination d_pfsense {
    file("/var/log/pfsense/remote.log" create-dirs(yes));
};

log {
    source(s_pfsense);
    destination(d_pfsense);
};
